# The Infrastructure as Code Action also supports integrating with GitHub Code Scanning and can show issues in the
# GitHub Security tab. When run, a snyk.sarif file will be generated which can be uploaded to GitHub Code Scanning.
name: Snyk Infrastructure as Code
on: push
jobs:
  snyk:
    runs-on: terraform-scanning
    permissions:
      contents: write
      packages: write
    defaults:
      run: 
       working-directory: ./
    env:
     TF_WORKSPACE: main

    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check configuration files for security issue
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severty-threshold=low
             --sarif-file-output=terraform.snyk.scan
          sarif: false
      - name: Upload result to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: terraform.snyk.scan
