name: Run tfsec sarif report
on:
  push:
    branches:
      - main
      - master
  pull_request:
jobs:
  tfsec:
    name: tfsec sarif report
    runs-on: terraform-scanning
    permissions: write-all
    defaults:
      run: 
       working-directory: ./modules

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: run report
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
          working_directory: modules/
          sarif_file: tfsec.sarif 
          tfsec_args: --force-all-dirs
          github_token: ${{ secrets.TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
